### ISSUE TITLE
Carriage returns in line endings prevent execution on linux

### ISSUE THREAD

**Issue by coderpatros** [Azure/Azurite#110]
When attempting to run `azurite` on linux I get this error `/usr/bin/env: ‘node\r’: No such file or directory`. A quick dos2unix on the file fixes it.

It looks like the line endings are ok in the repo. So maybe this is an issue introduced by the build/publish pipeline?

This is an issue for azurite 2.7.0 installed via npm and doesn't affect version 2.6.5

**Comment by clk1984** [comment]
Same issue for me .
Im running azurite on ubuntu 18.04.Any known solution ?

**Comment by patros** [comment]
@clk1984 

Run `which azurite` in a terminal to check the file path. It should be `/usr/local/bin/azurite`.

Then run `sudo dos2unix /usr/local/bin/azurite` to fix the line endings.

The other option is to specify version 2.6.5 when you install it. Use `azurite@2.6.5` instead of just `azurite` as the package name.

**Comment by XiaoningLiu** [comment]
@edwin-huber Can you take a look? Is this a regression?

**Comment by edwin-huber** [comment]
Cross platform support now in v3 being tested by Azure pipelines
