### ISSUE TITLE
Azure Service Bus

### ISSUE THREAD

**Issue by ehartford** [Azure/Azurite#1372]
Is it possible to add emulation for Azure Service Bus?

**Comment by ehartford** [comment]
https://github.com/Azure/azure-service-bus/issues/223

**Comment by SeanFeldman** [comment]
@ehartford Azurite is a storage emulator. Do not let the word 'emulator' confuse you. They are absolutely different things, Storage and Service Bus.

**Comment by edwin-huber** [comment]
Thanks for the suggestion, as @SeanFeldman states, Azure Service Bus is a different service, and not part of the storage APIs which we are emulating with this project.

**Comment by ehartford** [comment]
I figured.  Though storage queue and azure service bus are not so far apart
and there may be some synergy, if there were a meeting of the minds.  But I
understand. Thanks.

**Comment by pierrenoronha** [comment]
I'm using Azure functions triggered by Azure Service Bus, but I can run this on my local machine, because my company uses some environment security connection that create some thouble to execute locally.

How can I emulate Azure Service Bus if my environment use "Service Connection" to setup Service Bus?
