### ISSUE TITLE
[idea] fast load local files to azurite for testing

### ISSUE THREAD

**Issue by tg123** [Azure/Azurite#1537]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
N/A
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
N/A

### What problem was encountered?

bypass upload via http storage api, bulk load local folder to blob for testing

### Steps to reproduce the issue?

N/A

### Have you found a mitigation/solution?

N/A

**Comment by blueww** [comment]
@tg123 

Do you mean you would like Azurite can have a set of blob already setup (might has same structure as a local folder) when start , without upload any blob to it by rest API?

Since currently, besides the real blob content, azurite also maintain a complex set of metadata of the blobs, there's no easy way to just create a set of blobs from a local folder.
Besides that, upload blob to Azurite from same machine normally should be fast. Is there any specific reason you need the blobs be setup without uploading them?

**Comment by tg123** [comment]
in our test scenario, the test files are too large, up to 40G.
it took ~10-20m to upload them locally.
however, the downloading part is not fancy but some path base request without md5 or some other meta info.
