### ISSUE TITLE
Copy blobs with `if-none-match="*"` overwrites target but should return 409

### ISSUE THREAD

**Issue by roeap** [Azure/Azurite#1543]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the Azurite was used?

latest docker image

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub

### What's the Node.js version?

as in docker image

### What problem was encountered?

expected a 409 return when copying a blob to new location where an object already exists and the `If-None-Match` header is set to "*"

### Steps to reproduce the issue?
1. upload two blobs to service
2. try copying blob1 to blob2 location with `if-none-match="*"` header
3. operation should fail, but does succeed.

tested the same against storage account where we see expected behaviour.

### Have you found a mitigation/solution?

no

**Comment by blueww** [comment]
@[roeap](https://github.com/roeap)
Thanks for raising the issue, will looks into it and update you later.
BTW, why you would like to use `if-none-match="*"` header in copy blob? Why you just skip copy blob in this case?

**Comment by roeap** [comment]
this is for a rename-if-not-exists operation via copy-if-not-exists + delete and needed in concurrent scenarios.

**Comment by blueww** [comment]
@raeap

I can repro this issue and found the related code is in :https://github.com/Azure/Azurite/blob/ed364a411ea258c8e9d4317843e67e92efd39563/src/blob/conditions/WriteConditionalHeadersValidator.ts#L124

Currently differnent blob API has different behavior on `if-none-match="*"` header when blob exist, so this is still not handled so perfect in Azurite. We can't just throw error in above code since it will affect all blob write API, and might block other customers.

Azurite welcome contribution!
If you get a good resolution for this, it would be great if you can raise a PR to fix this.

**Comment by blueww** [comment]
This is already fixed in Azurite 3.18.0.
