### ISSUE TITLE
[Blob] Content-Encoding property missing from blob list items

### ISSUE THREAD

**Issue by roelarents** [Azure/Azurite#1698]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the Azurite was used?
v3.19.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
dockerhub or github (self build)

### What's the Node.js version?
v14.17.0

### What problem was encountered?
Some properties are missing compared to Azure in the blob items in the response for the blob list endpoint. E.g. `Content-Encoding`.

The API spec [lists these properties as included](https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs#response-body). 
This "inconsistency" with Azure causes a problem for e.g. minio azure gateway which [expects `Content-Encoding` to be present](https://github.com/minio/minio/blob/RELEASE.2022-03-26T06-49-28Z/cmd/gateway/azure/gateway-azure.go#L713).

### Steps to reproduce the issue?

* Run azurite with blob store enabled
* Create a container (publicly accessible, for the sake of simplicity) and upload a file into it. E.g. an empty txt file.
* Make a GET request to list the contents of that container  
  http://127.0.0.1:10000/devstoreaccount1/public/?comp=list&restype=container
* Look at the properties.
* To the same for a production blob storage account on Azure.
* Compare the properties of the Blob item. Azure includes `<Content-Encoding/>` and `<Content-Language/>`.  
  Azurite does not.

### Have you found a mitigation/solution?

I think the solution is somewhere in the XML serializer and/or the mapping for the BlobProperties. But that code is generated from the swagger specs (which I cannot find) with a private generator, [as stated in the readme](https://github.com/Azure/Azurite#typescript-server-code-generator). I could explicitly add the properties empty/undefined in the [`listBlobHierarchySegment`](https://github.com/Azure/Azurite/blob/main/src/blob/handlers/ContainerHandler.ts#L693) function. But they are removed somewhere in the serializer.

**Comment by blueww** [comment]
@roelarents 

From the swagger spec in [link](https://github.com/Azure/azure-rest-api-specs/blob/ec278eb936001b993e0413d66d8cc88e73540331/specification/storage/data-plane/Microsoft.BlobStorage/preview/2021-08-06/blob.json#L9741)
`<Content-Encoding/>` and `<Content-Language/>` are not required in the list blob responds. (only Etag and LastModified are required.) 
So Azurite will only add them when they really have value.

We have discussed [a similar issue](https://github.com/Azure/Azurite/issues/1592) for "Content-MD5" with server team before, and get :
"I think, empty element or absence of element should mean the same. Clients should be resilient while parsing XML response." 
That issue is for JS SDK, and finally JSD SDK is fixed to handle this kind of responds.

So this looks a client issue which can't handle the absence of these optional properties.
Would you like to contact the client team to fix the client side?

**Comment by roelarents** [comment]
Thanks for pointing to the swagger spec and the similar issue. You are right. So I'll close this issue. The client in question (minio azure gateway) unfortunately abandoned that functionality recently so I cannot change it there. But that's not your problem :). We'll find a workaround or other solution.
