### ISSUE TITLE
Start time shown in GMT and not local time

### ISSUE THREAD

**Issue by thinkOfaNumber** [Azure/Azurite#2310]
### Which service(blob, file, queue, table) does this issue concern?
Debugging using the workflow overview

### Which version of the Azurite was used?
v3.28.0

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Visual Studio Code Extension

### What's the Node.js version?
v16.14.0

### What problem was encountered?
The overview window shows local logic app runs in GMT, not local time

### Steps to reproduce the issue?
Create and run any logic app. Right click on the workflow.json file and select Overview

### Have you found a mitigation/solution?
No

I have searched for this issue but I'm new to logic apps and Azurite, so not sure if I'm looking in the right place. These start times are in GMT and not local time, however on the Azure portal, start times are shown in local time:
![image](https://github.com/Azure/Azurite/assets/5110983/5282f544-6009-4af2-afff-35403271b301)

**Comment by EmmaZhu** [comment]
Hi @thinkOfaNumber ,

From the description, I'm guessing what you are doing is: Start Azurite from VS Extension then leverage Azure Logic Apps to define a workflow for actions which may send request to Azurite to do some work?

The Start time shown in your screenshot seems from logic apps instead of Azurite. Azurite doesn't control how the time is shown, it should be logic app to control this. I think you can reach out to logic apps team (https://github.com/Azure/logicapps)  for further investigation.

Thanks
Emma

**Comment by thinkOfaNumber** [comment]
Thanks for being patient with me! I'm not quite sure which extension does what yet...

I start azurite using ctrl-shift-p `Azurite: start`, and that has to be running otherwise I can't view the output so I assumed it was an Azurite thing.

I'll jump over to the other repo and check it out.

thanks

**Comment by EmmaZhu** [comment]
This is not an Azurite issue. If any further help needed, please feel free to reopen the issue.
