### ISSUE TITLE
Azurite cannot handle encoded blob names

### ISSUE THREAD

**Issue by viswanr** [Azure/Azurite#2405]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
3.29.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub/MCR
### What's the Node.js version?
18
### What problem was encountered?

We are running an integration test written in Typescript using Docker, where we have a container with our Java Function app an d it calls to into Azurite, the official storage emulator from Azure. The Java Azure Function is running in Docker along with Azurite within the same network.

The PUT request to upload the file to Azurite is as follows, which is successful:
 "PUT /devstoreaccount1/tdigests/hourlyDigests/v2/EMEA/t2_1/ChatSwitch/eyJBcHBJbmZvX0NsaWVudFR5cGUiOiJ3ZWIiLCJBcHBJbmZvX0Vudmlyb25tZW50IjoicHJvZCIsIkFwcEluZm9fRXhwZXJpZW5jZU5hbWUiOiJyZWFjdC13ZWItY2xpZW50IiwiRGVyaXZlZF9Vc2VySW5mb19FZHVUeXBlIjoiRURVIiwiY29udGV4dFR5cGUiOiJ0Ml8xIiwiZXZlbnROYW1lIjoiY2hhdF9zd2l0Y2giLCJncm91cGluZ05hbWUiOiJBcHBJbmZvX0NsaWVudFR5cGUiLCJtZXRyaWNLaW5kIjoibGF0ZW5jeSJ9/2024-04-07/21/tdigests.json HTTP/1.1" 201

Now, when we look at the URL that the Java app is using for the GET request,

 "GET /devstoreaccount1/tdigests/hourlyDigests%2Fv2%2FROW%2Ft2_1%2FChatSwitch%2FeyJBcHBJbmZvX0NsaWVudFR5cGUiOiJ3ZWIiLCJBcHBJbmZvX0Vudmlyb25tZW50IjoicHJvZCIsIkFwcEluZm9fRXhwZXJpZW5jZU5hbWUiOiJyZWFjdC13ZWItY2xpZW50IiwiRGVyaXZlZF9Vc2VySW5mb19FZHVUeXBlIjoiRURVIiwiY29udGV4dFR5cGUiOiJ0Ml8xIiwiZXZlbnROYW1lIjoiY2hhdF9zd2l0Y2giLCJncm91cGluZ05hbWUiOiJTY2VuYXJpb19TdGF0dXMiLCJtZXRyaWNLaW5kIjoibGF0ZW5jeSJ9%2F2024-04-07%2F23%2Ftdigests.json HTTP/1.1" 404

As you can see, the slashes in the path are being encoded. Consequently, this is causing the following 404 issue where it cannot find the blob (since the path is wrong because of the encoding). The download path is not encoded before the GET request is sent, but it seems like it is getting encoded during transit to Azurite.

This behavior seems to happen only in the Java SDK. We have similar setups with .NET and Nodejs Function apps, and they work well with Azurite.
https://github.com/Azure/azure-sdk-for-net/pull/30271

Here is an issue we filed on the Java SDK - https://github.com/Azure/azure-sdk-for-java/issues/40370

Since the actual Azure Blob Storage service in production treats slashes and %2F the same, Azurite should emulate the same.

### Steps to reproduce the issue?

If possible, please provide the debug log using the -d parameter, replacing \<pathtodebuglog\> with an appropriate path for your OS, or review the instructions for docker containers:

```
-d "<pathtodebuglog>"
```

Please be sure to remove any PII or sensitive information before sharing!  
The debug log will log raw request headers and bodies, so that we can replay these against Azurite using REST and create tests to validate resolution.

**Comment by blueww** [comment]
@viswanr 

Thanks for raising this issue!

Do you mean you upload/download same blob with different Uri, upload with not encoded uri, download with encoded uri? 
If you could share the Azurite debug log, we can be more clear on which Uri Azurite receive. 

If this is the case, and if the different Uris both work on product Azure, this issue looks an undocumented behavior of product Azure. 
It will take time to add this support the Azurite, since if there are no clear doc for this behavior, we need first contact server team and try to get a clear picture of how this feature works, include all cornet cases. It might take a long time.
Besides that, we also has other feature requests on hand, we will priority this item together with other feature items, and this item might won't be our highest priority in the recent future.

As you said , this issue only occur on Java SDK but not .net and js SDK, so this looks more like a Java SDK issue, since it upload/download same blob with different Uri. 
I see you have already opened an issue for Java SDK. It would be better if Java SDK could fix this issue.

**Comment by viswanr** [comment]
@blueww 

1. The PUT url and the GET url above are pulled out from the Azurite log as Azurite sees it. Yes, the PUT request isn't encoded. But the GET is encoded. Azurite should still properly map ` / to %2F` and vice versa. 
2. The actual Azure Blob Storage service does treat them to be similar. From the [documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata), it's clear that:
"Reserved URL characters must be properly escaped.". So technically, Azurite should understand, and this is not undocumented behavior. 

cc: @alzimmermsft

**Comment by blueww** [comment]
@viswanr 

For "/" in blob name, it's a little different in doc. 
In the [documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata) from your above comment, it says:

1. "Certain characters must be percent-encoded to appear in a URL, using UTF-8 (preferred) or MBCS. This encoding occurs automatically when you use the Azure Storage client libraries."  However, per my testing, current storage client libraries  won't encode "/" in storage blob path. So "/" is not in the certain characters need encode.
2. For blob name, it says "A path segment is the string between consecutive delimiter characters (for example, a forward slash /) that corresponds to the directory or virtual directory." So "/" is used as path segment delimiter, instead of normal char that need encoded.
 
Azurite already has a complex logic to handle "/" and "\\" in the Uri (for corner cases), and have get customer issues for regression caused some before changes on this part. So please understand we need to investigate and get the whole picture of the server behavior on this case, then see how to apply it to Azurite to avoid regression as much as possible. This will take time.

A better way is Java App fixing code to upload/download same blob with same Uri. It's really abnormal for same application/library handle same object with different kind of Uri.

**Comment by blueww** [comment]
@viswanr 

I just tested on latest Azurite 3.30.0, and replace "/" to "%2F" in blob name, the Uri still works on Azurite (test with Getblob request). So it looks the encoded blob name already works on Azurite. 

Besides that, in the upload/download Uri you provide, I see they are no point to same blob. 
Upload point to "hourlyDigests/v2/ROW/..." , download point to "hourlyDigests/v2/EMEA/...". 

To continue investigation, would you please provide Azurite debug log (collect with "-d" parameter) for upload/download on same blob?
