### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by xaxdev** [Azure/Azurite#248]
- Issue Type: `Performance`
- Extension Name: `azurite`
- Extension Version: `3.1.2`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.34.0`

:warning: Make sure to **attach** this file from your *home*-directory:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by XiaoningLiu** [comment]
@xaxdev CPU usage is related to Azurite workload. When this warning happens, did Azurite have a heavy usage?

**Comment by rwecho** [comment]
I have the same question. but I'm use linux docker.  It shows node cpus useage 100%.
``` bash 
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
27386 root      20   0  752992 515044  31584 R 100.7  1.6 200:31.52 node   
```

**Comment by rwecho** [comment]
When I specify the volumn as local disk . The cpu useage recover normal. 
I'm not sure if it causes. 
Long-term observation

``` bash
  docker run -v azurite:/data  -p 10000:10000 -d --rm mcr.microsoft.com/azure-storage/azurite
# cpu: 100%
```
 ```  bash
docker run -v ~/app/azurite:/data  -p 10000:10000 -d --rm mcr.microsoft.com/azure-storage/azurite
# cpu: normal
```

**Comment by rwecho** [comment]
It appears cpu 100% again . 
when it runs for a time, it will eat my cpu.

``` bash
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                       
 6658 root      20   0  334020 104908  32008 R 100.0  0.3   4:49.74 node                                                                                                                                          
24383 root      20   0 2680216 150940  49788 S   3.6  0.5 113:04.48 dockerd    
```

**Comment by XiaoningLiu** [comment]
@rwecho

 Couple of questions here:

* Can you try execute Azurite in physical machien instead of docker? This is to check the issue is in Azurite, or docker runtime.
* Will CPU still reaches 100% when "specify the volumn as local disk"?
* What's the workload of Azurite when CPU reaches 100%?  In our previous testing, for upload scenario, CPU will reach to 100% when upload speed reaches 300MB/s. The testing is in physical machine, instead of docker. I'm courious about the overload, such as QPS, ingress and egress. You can share access log or debug log in the 100% cpu time period.

We can add throttling logic to Azurite if this issue is expected due to high workload . This strategy will reject part of requests when CPU usage is high. All storage client SDKs have retry policy to deal with throttling situation.

**Comment by rwecho** [comment]
@XiaoningLiu 
After summary, I doubt the reason is that a lot of files lead to it.

Once I upload a set of files (more than fifty thousand), the cpu will reach 100%.
No matter what I restart docker or restart host server, and when I rename the persist folder or clear up the /data. The cpu will recover normal.

I'll try in physical machine and feedback here.

**Comment by rwecho** [comment]
@XiaoningLiu 
 
I try in physical machine. The question still exists.

there is more than 78000 files in directory __blobstorage__ , total size > 2.3G

file __azurite_db_blob__.json > 76M

Is the number and size is too big and cause the disk IO too slowly ?

**Comment by XiaoningLiu** [comment]
@rwecho I think so. Loki based implementation will sync in memory metedata to disk peridly. While file number grows, the data needs to sync every time grows. I have investigated implementation based on SQLlite, however it doesn't fit the cross platform Visual Studio Code extension. We are also investigating a metadata layer implementation based on SQL ORM.

Curious, are you using Azurite for testing with that amount of data?

**Comment by rwecho** [comment]
@XiaoningLiu 
I have a big image, cut it to thousands of tiles for uploading. 
Now I test it using Azurite in my local environment, prepare for product in Azure Storage.

**Comment by XiaoningLiu** [comment]
@rwecho Thanks! CPU usage highly relates to usage pattern.

**Comment by XiaoningLiu** [comment]
3.3.0-preview npm package and docker image adds support external SQL database as metadata storage used by Azurite. This helps Azurite scale out when persisted data grows. Welcome to take a try!

https://github.com/azure/azurite#customized-metadata-storage-by-external-database-preview
