### ISSUE TITLE
Support for HTTPS endpoints - possible ?

### ISSUE THREAD

**Issue by seguler** [Azure/Azurite#38]
See the request here: https://feedback.azure.com/forums/217298-storage/suggestions/10221816-add-support-for-https-endpoints-to-azure-storage-e 

What would it take to support an HTTPS endpoint ? Could we do it withy dummy certs ?

**Comment by edwin-huber** [comment]
This is a relatively simple enhancement.
Azurite currently uses express, which just needs a certificate passed in to the listener when the server is created:

[https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener](https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener)

Developers wishing to test with HTTPs would need to provide their own trusted certificates etc, but adding a few lines to read command line args with cert path, and an appropriate test case should not be too difficult.

**Comment by eriksteinebach** [comment]
This would be very useful for us

**Comment by edwin-huber** [comment]
We have since dramatically changed the architecture and moved to typescript.  
Theoretically, we can add support for configuring HTTPS see:
https://timonweb.com/posts/running-expressjs-server-over-https/  
We have quite a backlog right now, but @eriksteinebach maybe you can give us some more background on your HTTPS requirement for the emulator?  
Would a selfsigned cert be enough, and if so, name bound to localhost address?

**Comment by eriksteinebach** [comment]
Hi, yes I think that would support our workflow. I ended up here because we have some scss files being generated on startup of our app into css files and stored in azure storage. Then they are directly referenced in our app. This works fine in prod, because azure storage uses https. But locally for testing we need to click on the accept mixed content message which I wanted to get rid of.

We use a docker image so we would have to be able to add the selfsigned cert on startup (or make our own image on top of yours). We would have to add it to our root certs, although not ideal, it is better than what we have now (because only a 1 time action) and I don't think there is a better way seeing the emulator is fixed on the localhost addresses?

**Comment by thisisthekap** [comment]
@eriksteinebach You could consuder to use a separate docker container as https reverse proxy, or a service like ngrok (ngrok.io).

**Comment by edwin-huber** [comment]
I would recommend just setting up an nginx with the required certs and proxy config:  
https://www.nginx.com/blog/nginx-ssl/  

@eriksteinebach  which APIs are you looking to use this with?  
Based on your comment, it looks like just blob storage, which means we would need to check support with in our v3 architecture, correct?

**Comment by eriksteinebach** [comment]
@edwin-huber correct, it would be for blob storage, but we do also use Azure queues (but ssl is less important there, because it is just for local development).

We did see the option to use a reverse proxy at the time, but because of the added complexity we didn't opt to go for that at the time, but I think we need to revisit it. It is probably our best option at the moment. I like to keep things as simple as I can.

**Comment by XiaoningLiu** [comment]
It should not a big change in V3 to change to support HTTPS https://github.com/Azure/Azurite/blob/c716f1e3e87e061c4cae406fd36a26492d62017a/src/blob/BlobServer.ts#

**Comment by CastleArg** [comment]
+1 on this.  
My situation is using blob storage as a SQL external data source.
I found out a little late this would not run locally, due to sql requiring https.

**Comment by XiaoningLiu** [comment]
@CastleArg Just curious do you needa local deployment of SQL external data source for production or testing usage?

We will investigate it in V3. In the meantime, contributions are welcome!

**Comment by jongio** [comment]
This is going to be needed to support the new Azure SDKs and DefaultAzureCredential, since TokenCredential requires HTTPS.  Would be great to see this implemented.

**Comment by jongio** [comment]
As a stopgap to help customers use Azurite with HTTPS today. I posted a blog on how to use an HTTPS-HTTP reverse proxy in this blog post: https://blog.jongallant.com/2020/02/azurite-https-defaultazurecredential/

**Comment by jongio** [comment]
FYI - Storage Explorer update to support HTTPS on emulator screen is dependent on Azurite supporting HTTPS natively: See comment here: https://github.com/microsoft/AzureStorageExplorer/issues/2598#issuecomment-584290794

**Comment by jongio** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/19399 - to get working with `dotnet dev-certs`

**Comment by XiaoningLiu** [comment]
Azurite v3.7.0 supports HTTPS endpoint and OAuth.

**Comment by SeanFeldman** [comment]
Given that v3.7.0 is out, should this issue be closed as completed?

**Comment by blueww** [comment]
Close the issue as https is already supported from 3.7.0
