### ISSUE TITLE
Blob metadata forced lower case

### ISSUE THREAD

**Issue by NiklasArbin** [Azure/Azurite#380]
### Which service(blob, file, queue, table) does this issue concern?
Blob
### Which version of the Azurite was used?
3.4.0
### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub
### What's the Node.js version?
-
### What problem was encountered?
Blob metadata is lowercased
### Steps to reproduce the issue?
Store blob metadata in mixed casing. Retrieve blob and fetch attributes. Metadata casing is now forced lower case.
### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
@NiklasArbin 
Thanks for reporting the issue!
I can repro it, and see the metadata key will be lower case. (metadata value will keep case)
We will fix it in a future release.

**Comment by ayeltsov** [comment]
@blueww , @XiaoningLiu - I wanted to familiarize myself a bit with this emulator and code base, and dug a bit into the matter - especially that our team is also affected by the issue

It looks like the problem roots in API choice of transmitting custom metadata as HTTP key-value header pairs. And per HTTP RFC, the header keys are case-insensitive (see [discussion ](https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive) on stack overflow, also it looks like HTTP/2 goes even further and is required to lowercase header keys)

Specifically, lowercasing happens in node's [_http_incoming.js](https://github.com/nodejs/node/blob/a17131400360562f06fc4d1c217ee60f7c5928aa/lib/_http_incoming.js#L252) and is by design. One possible workaround - would be to check original pre-lowercased headears (if available) when considering metadata.

**Comment by XiaoningLiu** [comment]
Hi guys,

Sorry for the late response as we are in holiday. Thanks for @ayeltsov 's investigation! For your question. `deserializer.middleware.ts` will deserialize incoming HTTP requests and initialize the option objects. While `HandlerMiddlewareFactory.ts` will invoke the handler methods and pass the option object values.

The deseriazalition code path is based on swagger generated artifacts and shared by all RESTful APIs.

@blueww and me is thinking another way that whether we can directly go to handler `setMetadata` implementation, and in the implementation, get the raw incoming http request headers and keeping the case.

**Comment by blueww** [comment]
@NiklasArbin

After do more investigation, we find metadata key should not be expected to be case-sensitive.
Metadata is a http header, and http header is case insensitive. See : https://tools.ietf.org/html/rfc2616 4.2: "Field names are case-insensitive."

So client code should not compare metadata key with case sensitive. 
Would you please fix your client code, to compare metadata key with case insensitive?

**Comment by ayeltsov** [comment]
@blueww - unfortunately, production is already implemented in case-sensitive way. 

When we have to chose between RFC correctness and emulating production behavior, I belive we should snap to production behavior. 

Also please note that it's not easy to implement your suggestion - "client code should not compare metadata key with case sensitive":
- Production will not find metadata entries if we do not supply exact case. So **we must continue supplying "correct" case in production code**.
- However, while production will return metadata entries in that same case, currently Emulator will change the case to lowercase upon return. This means more complex handling with different code paths for production and emulator, hence increased chance of bugs.

So, while unforunate, I would vote to fix this on the emulator side.

**Comment by XiaoningLiu** [comment]
Got a workaorund to parser cases from raw headers, will update in v3.6.0
