### ISSUE TITLE
Failed to reach azurite blob on 127.0.0.1

### ISSUE THREAD

**Issue by ncarenton** [Azure/Azurite#715]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the Azurite was used?

mcr.microsoft.com/azure-storage/azurite latest 7883f51238b3

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)

DockerHub

### What problem was encountered?

Failed to reach azurite blob on 127.0.0.1

### Steps to reproduce the issue?

```
nicolas@nicolas > docker run -p 10000:10000 -p 10001:10001 mcr.microsoft.com/azure-storage/azurite azurite-blob
Azurite Blob service is starting on 127.0.0.1:10000
Azurite Blob service successfully listens on http://127.0.0.1:10000
nicolas@nicolas > curl http://127.0.0.1:1000
curl: (7) Failed to connect to 127.0.0.1 port 1000: Connection refused
```

### Have you found a mitigation/solution?

Specifying `blobHost=0.0.0.0` this way works but is potentially unsafe as mentioned [here](https://github.com/Azure/Azurite/blob/master/README.md#allow-accepting-requests-from-remote-potentially-unsafe)
Did I miss a parameter or something so service can be reached on 127.0.0.1 ?

```
nicolas@nicolas > docker run -p 10000:10000 -p 10001:10001 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost=0.0.0.0 
Azurite Blob service is starting on 0.0.0.0:10000
Azurite Blob service successfully listens on http://0.0.0.0:10000
nicolas@nicolas > 
```

**Comment by blueww** [comment]
@ncarenton 
The "potentially unsafe" is caused by other computer in same network, might can access azurite on 0.0.0.0. (with 127.0.0.1, only process on local machine can access it.)

For Docker, we can take it as a kind of virtual machine, so we need cross  machine boundary to access azurite on it, and only 0.0.0.0 works. (127.0.0.1 not work.)

In [Readme.md](https://github.com/Azure/Azurite#dockerhub), you can see  a sample for just run blob service with docker, it also need "--blobHost 0.0.0.0"
You can also find `If you use customized azurite paramters for docker image, --blobHost 0.0.0.0, --queueHost 0.0.0.0 are required parameters.` So if you add any paramters besides the first sample in [dockerhub ](dockerhub) section (like "azurite-blob"), you need to add "--blobHost 0.0.0.0" to run blob request and "--queueHost 0.0.0.0" to run queue service.

**Comment by ncarenton** [comment]
Thanks @blueww !

**Comment by swimhiking** [comment]
I use the docker,  and got this error "ExtendedSocketException: Connection refused [::ffff:0:0]:10000"; looks I use 0.0.0.0 as the blobHost. see attached image. how to fix this? Thanks
![image](https://user-images.githubusercontent.com/6053471/126509187-3f530bcd-c52b-4f1f-be15-d9dc76a58f30.png)

**Comment by blueww** [comment]
@swimhiking

As this is anther issue, it's better to open a new issue. If you following the issue template, we should can get most information needed to investigate (like Azurite version, the command to start Azurite, the debug log).

For your issue, you might can try to use 127.0.0.1 instead of 0.0.0.0. (0.0.0.0 is on docker, and your program to access azurite runs on local machine).
If this not work, please open a new issue.
