### ISSUE TITLE
Azurite for docker can not find .pem files

### ISSUE THREAD

**Issue by anpaskin** [Azure/Azurite#721]
### Which service(blob, file, queue, table) does this issue concern?
Queue

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
DockerHub

### What problem was encountered?
I am trying to enable HTTPS for my Azurite docker container, but the .pem files I generated with mkcert can not be found.

### Steps to reproduce the issue?
Following these instructions: https://github.com/Azure/Azurite/blob/master/README.md#https-setup
1. Install mkcert (I used `choco install mkcert`)
2. Run:
```
mkcert -install
mkcert 127.0.0.1
```
3. Pull the Azurite docker container: 
```
docker pull mcr.microsoft.com/azure-storage/azurite
```
4. Run a container with HTTPS enabled using the --cert and --key arguments pointing to the generated .pem files:
```
docker run --name storage -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-queue --cert 127.0.0.1.pem --key 127.0.0.1-key.pem --loose --queueHost 127.0.0.1
```
Result:
```
Exit due to unhandled error: ENOENT: no such file or directory, open '127.0.0.1.pem'
```
yet the file exists in the directory in which I am running the docker command:

![image](https://user-images.githubusercontent.com/33612256/111383006-e7476700-8664-11eb-942e-ce7d2ee87477.png)

I've tried supplying the absolute paths to the .pem files as well and got the same result.

**Comment by blueww** [comment]
@anpaskin 

The cert file is on you local machine, to make docker can access the cert file, you need to map the folder contains the files to docker. (in following sample, I map local folder  `c:/azurite` to `/workspace` on docker )
Besides that, The queue port on Azurite is 10001 by default, so need map the 10001 port on docker with `-p 10001:10001`
And we can take docker as a VM, so to access it we need cross machine boundary. Then we need use `--queueHost 0.0.0.0` instead of 127.0.0.1.

The command work for on my machine is ("c:/azurite" contains the cert file): 
```powershell
docker run --name storage -p 10001:10001 -v c:/azurite:/workspace   mcr.microsoft.com/azure-storage/azurite azurite-queue --cert /workspace/127.0.0.1.pem --key /workspace/127.0.0.1-key.pem --queueHost 0.0.0.0 --loose
```

**Comment by anpaskin** [comment]
These changes worked, thank you!

As a side note for anyone returning to this issue, I'm working in Linux and in order to add my certificates to the trusted root store, I had to copy the certs to `/usr/local/share/ca-certificates/`, rename them to have the `.crt` extension, and then run `sudo update-ca-certificates`.
