### ISSUE TITLE
How to use ansible azcollection ?

### ISSUE THREAD

**Issue by pgstef** [Azure/Azurite#835]
Hi,

First of all, thanks for the awesome project.

I'm currently running the docker image for dev purposes. And I'm wondering how to simply create a container.

I first tried to use the Rest API but the sign part of Authorization header isn't very easy to produce using cUrl.

So, I was wondering if the [ansible collection](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_storageblob_module.html) could be used with Azurite. I don't really see how I could provide a connection string or change the endpoint to use it.

Would you have any advice to share please?

Many thanks in advance,
Kind regards

**Comment by blueww** [comment]
@pgstef 

Thanks for using Azurite!

This issue is more like a question for ansible collection， than a question for Azurite.
I am not familiar with ansible collection. But if you can use it to create container on Azure server, you should can use the similar way to create container on Azurite.

Besides that, if it's difficult for you on " sign part of Authorization header", you can use existing SDK instead of using rest API directly, and they can help you to construct the sign part. （e.g.: [.net SDK sample to create container](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-container-create?tabs=dotnet)）
Or you can use SAS credential. You can create an [account SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas) with enough permission, and add the SAS to the Uri.

**Comment by pgstef** [comment]
Hi,

Unfortunately, I didn't succeeded to use that ansible collection with Azurite, given that the only authentication method they seem to provide are based on [az login](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest). I simply couldn't find how to point to the Azurite endpoint.

Using the .net SDK inside an ansible playbook is not that easy too. I currently rely on shell commands:

```
    DATE_ISO=$(TZ=GMT date "+%a, %d %h %Y %H:%M:%S %Z")
    VERSION="2020-08-04"
    HEADER_RESOURCE="x-ms-date:$DATE_ISO\nx-ms-version:$VERSION"
    URL_RESOURCE="/$STORAGE_ACCOUNT/$STORAGE_ACCOUNT/$CONTAINER_NAME\nrestype:container"
    STRING_TO_SIGN="PUT\n\n\n\n\n\n\n\n\n\n\n\n$HEADER_RESOURCE\n$URL_RESOURCE"
    DECODED_KEY="$(echo -n $STORAGE_KEY | base64 -d -w0 | xxd -p -c256)"
    SIGN=$(printf "$STRING_TO_SIGN" | openssl dgst -sha256 -mac HMAC -macopt "hexkey:$DECODED_KEY" -binary |  base64 -w0)
    curl -X PUT --silent --insecure \
      -H "x-ms-date:$DATE_ISO" \
      -H "x-ms-version:$VERSION" \
      -H "Authorization: SharedKey $STORAGE_ACCOUNT:$SIGN" \
      -H "Content-Length:0" \
      "https://{{IPAddress}}/$STORAGE_ACCOUNT/$CONTAINER_NAME?restype=container"
```
But that way of doing isn't really reliable since I can't handle the HTTP return codes.

I guess I'll have the same issue if I want to create SAS account. I first have to find a way to do it via the ansible playbook.

Any way, thanks for your answer, I'll see if I can ask on the ansible collection the same question.

Kind Regards

**Comment by edwin-huber** [comment]
My recommendation is to create a long term SAS key using another tool like the storage explorer, you should then be able to use that with curl.

**Comment by blueww** [comment]
@pgstef

As this is not an Azurite question, I will close this issue.
Feel free to contact us if you need any further Azurite support.

**Comment by edwin-huber** [comment]
Maybe we can take a task to update our documentation, to show how to use Curl with Azurite? 
It seems that this type of question has come up a few times now.
