### ISSUE TITLE
ETag not determined from GET request on table in Orleans.

### ISSUE THREAD

**Issue by arnoldpistorius** [Azure/Azurite#946]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the Azurite was used?
Both legacy (v2) and main (v3)

### Where do you get Azurite? (npm, DockerHub, NuGet, Visual Studio Code Extension)
Github

### What's the Node.js version?
10.6

### What problem was encountered?
ETag is not populated from GET in Orleans Grain state, while it is when the requests are made against a 'real' Azure Storage account.

### Steps to reproduce the issue?
See https://github.com/arnoldpistorius/orleans-azurite-entityalreadyexists for a repro demo.

### Have you found a mitigation/solution?
Use real Azure Storage instead of Azurite (but we want to use Azurite for local development)

**Comment by edwin-huber** [comment]
Thanks for reporting.
I'm taking a look at the issue.

**Comment by michaelmcneilnet** [comment]
I was having the same issue, seems to have been fixed in the latest Azurite docker image

**Comment by edwin-huber** [comment]
Thanks for following up.
I'm just checking that this issue is properly resolved.

**Comment by edwin-huber** [comment]
The issue exists because we respond based on API Spec, and the service / old emulator responds with an ETag to OData nometadata.

The ETag is indeed important and it is used to determine whether an Insert or an Upsert is issue. i.e, an Insert is made instead of an Upsert because no ETag was returned in the GET call.

A recent PR migrated to the new Azure Table Storage SDK and that removed that “no metadata” setting. That should fix this issue for future versions of Orleans (3.6.0+, which isn’t released yet).
See: https://github.com/dotnet/orleans/pull/7431

We shall update Azurite to respond with an Etag on Odata nometadata requests to match the service.

**Comment by arnoldpistorius** [comment]
I can confirm that everything behaves well with the latest container release.

**Comment by edwin-huber** [comment]
closing issue
